create table if not exists public.orders (
  id bigint generated by default as identity (start with 72481) constraint orders_1_pkey primary key,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone,
  merchant_id uuid,
  payment_provider_id bigint references public.payment_providers,
  shipping_method_id bigint references public.shipping_methods,
  total_quantity numeric,
  total_amount numeric constraint check_total_amount check (total_amount >= (0) :: numeric),
  shipping_fee numeric constraint check_shipping_fee check (shipping_fee >= (0) :: numeric),
  insurance_fee numeric constraint check_insurance_fee check (insurance_fee >= (0) :: numeric),
  discount numeric constraint check_discount check (discount >= (0) :: numeric),
  status varchar,
  buyer_account_id uuid,
  order_no varchar,
  shipping_address_id bigint,
  delivery_metadata jsonb,
  checkout_id uuid,
  discount_metadata json,
  awb_no varchar,
  payment_hash text,
  payment_token text,
  payment_bin varchar,
  promo_ids jsonb,
  warehouse_id bigint,
  created_by uuid,
  updated_by uuid,
  cancel_by uuid,
  cancel_notes text,
  commission_fee numeric constraint check_commission_fee check (commission_fee >= (0) :: numeric),
  delivered_at timestamp with time zone,
  pickup_at timestamp with time zone,
  platform varchar,
  ref_id integer,
  shipping_discount numeric constraint check_shipping_discount check (shipping_discount >= (0) :: numeric),
  seller_metadata jsonb,
  recipient_metadata jsonb,
  source varchar
);

create table if not exists public.order_list (
  id uuid default uuid_generate_v1() not null primary key,
  product_variant_id uuid,
  quantity numeric constraint check_quantity check (quantity >= (0) :: numeric),
  amount numeric constraint check_amount check (amount >= (0) :: numeric),
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone,
  order_id bigint not null references public.orders on delete cascade,
  product_metadata json,
  ref_id integer
);

create table public.account_transactions (
  id bigint generated by default as identity constraint account_transaction_1_pkey primary key,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  status varchar,
  buyer_account_id uuid,
  amount numeric constraint check_amount check (amount >= (0) :: numeric),
  checkout_id uuid unique,
  payment_metadata json,
  payment_bill_metadata json,
  ref_id bigint,
  billing_address_id bigint,
  billing_address_metadata json
);

create table public.order_histories (
  id uuid default extensions.uuid_generate_v4() not null primary key,
  created_at timestamp with time zone default now(),
  order_id bigint not null,
  descriptions text,
  data json
);

create table if not exists public.order_transactions (
  id bigint generated by default as identity constraint order_transactions_1_pkey primary key,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone,
  account_transaction_id bigint references public.account_transactions,
  order_id bigint references public.orders on delete cascade,
  amount numeric constraint check_amount check (amount >= (0) :: numeric),
  ref_id bigint
);

create table if not exists public.shipping_methods (
  id bigint generated by default as identity primary key unique,
  code varchar,
  type varchar,
  name varchar,
  status boolean,
  icon text,
  shipping_provider_id bigint
);

create table public.categories (
  id bigint generated by default as identity constraint categories_1_pkey primary key,
  name varchar constraint categories_un unique,
  description text,
  position integer,
  parent_id bigint,
  media_url json,
  status status,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone,
  is_selectable boolean,
  images json,
  meta_title varchar,
  slug text,
  meta_keyword text,
  meta_description text
);

create table public."3pl_provinces" (
  id bigint generated by default as identity primary key,
  code bigint unique,
  parent bigint,
  name varchar,
  latitude varchar,
  longitude varchar,
  postal varchar,
  province_id bigint references public.provinces
);

create table public."3pl_cities" (
  id bigint generated by default as identity primary key,
  code bigint unique,
  parent bigint,
  name varchar,
  latitude varchar,
  longitude varchar,
  postal varchar,
  city_id bigint references public.cities,
  province_id bigint references public."3pl_provinces"
);

create table public."3pl_districts" (
  id bigint generated by default as identity primary key,
  code bigint unique,
  parent bigint,
  name varchar,
  latitude varchar,
  longitude varchar,
  postal varchar,
  district_id bigint,
  city_id bigint references public."3pl_cities"
);