create type public.todo_status as enum ('TODO', 'IN_PROGRESS', 'COMPLETE');

create table if not exists public.todos (
    id bigint generated by default as identity constraint todos_pkey primary key,
    account_id bigint references public.accounts,
    status public.todo_status default 'TODO'::todo_status,
    title varchar,
    description text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone
);