create table if not exists public.accounts (
    id bigint generated by default as identity constraint accounts_pkey primary key,
    name varchar,
    email varchar,
    password text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone
);